# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\netuser003\Documents\manop\Branch\asset\Scandisplay_without_label_IDC.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1095)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 5, 1900, 1057))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.PPE = QtWidgets.QWidget()
        self.PPE.setObjectName("PPE")
        self.Countnum = QtWidgets.QLCDNumber(self.PPE)
        self.Countnum.setGeometry(QtCore.QRect(620, 10, 110, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Countnum.setFont(font)
        self.Countnum.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.Countnum.setSmallDecimalPoint(False)
        self.Countnum.setDigitCount(2)
        self.Countnum.setProperty("value", 30.0)
        self.Countnum.setProperty("intValue", 30)
        self.Countnum.setObjectName("Countnum")
        self.DateTim = QtWidgets.QDateTimeEdit(self.PPE)
        self.DateTim.setGeometry(QtCore.QRect(1200, 30, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.DateTim.setFont(font)
        self.DateTim.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DateTim.setStyleSheet("color:rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"padding-right:60px;\n"
"\n"
"")
        self.DateTim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DateTim.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.DateTim.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 10, 10)))
        self.DateTim.setObjectName("DateTim")
        self.lblcategory = QtWidgets.QLabel(self.PPE)
        self.lblcategory.setGeometry(QtCore.QRect(20, 24, 581, 76))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lblcategory.setFont(font)
        self.lblcategory.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-top-left-radius: 20px; \n"
"border-top-right-radius: 20px; \n"
"border-bottom-left-radius: 0px; \n"
"border-bottom-right-radius: 0px; ")
        self.lblcategory.setAlignment(QtCore.Qt.AlignCenter)
        self.lblcategory.setObjectName("lblcategory")
        self.cameraview = QtWidgets.QGraphicsView(self.PPE)
        self.cameraview.setGeometry(QtCore.QRect(20, 100, 981, 731))
        self.cameraview.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid gray;\n"
"")
        self.cameraview.setObjectName("cameraview")
        self.labelEquipment = QtWidgets.QLabel(self.PPE)
        self.labelEquipment.setGeometry(QtCore.QRect(1500, 90, 351, 121))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelEquipment.setFont(font)
        self.labelEquipment.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelEquipment.setObjectName("labelEquipment")
        self.lblGood = QtWidgets.QLabel(self.PPE)
        self.lblGood.setGeometry(QtCore.QRect(420, 850, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblGood.setFont(font)
        self.lblGood.setStyleSheet("background-color: rgb(2, 102, 17);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.lblGood.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGood.setObjectName("lblGood")
        self.labelRef = QtWidgets.QLabel(self.PPE)
        self.labelRef.setGeometry(QtCore.QRect(1030, 100, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.labelRef.setFont(font)
        self.labelRef.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelRef.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 20px; \n"
"border-top-right-radius: 20px; \n"
"border-bottom-left-radius: 0px; \n"
"border-bottom-right-radius: 0px; ")
        self.labelRef.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Reference</span></p></body></html>")
        self.labelRef.setTextFormat(QtCore.Qt.RichText)
        self.labelRef.setWordWrap(False)
        self.labelRef.setObjectName("labelRef")
        self.lblNG = QtWidgets.QLabel(self.PPE)
        self.lblNG.setGeometry(QtCore.QRect(630, 850, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblNG.setFont(font)
        self.lblNG.setStyleSheet("background-color: rgb(145, 0, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.lblNG.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNG.setObjectName("lblNG")
        self.lblTotal = QtWidgets.QLabel(self.PPE)
        self.lblTotal.setGeometry(QtCore.QRect(210, 850, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotal.setFont(font)
        self.lblTotal.setStyleSheet("background-color: rgb(193, 113, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setObjectName("lblTotal")
        self.groupBox = QtWidgets.QGroupBox(self.PPE)
        self.groupBox.setGeometry(QtCore.QRect(1485, 215, 391, 666))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setStyleSheet("background-color: none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 351, 1030))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Safety_Shoe = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Safety_Shoe.setMinimumSize(QtCore.QSize(231, 68))
        self.Safety_Shoe.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Safety_Shoe.setFont(font)
        self.Safety_Shoe.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"\n"
"")
        self.Safety_Shoe.setAlignment(QtCore.Qt.AlignCenter)
        self.Safety_Shoe.setObjectName("Safety_Shoe")
        self.gridLayout.addWidget(self.Safety_Shoe, 8, 1, 1, 1)
        self.OSL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.OSL.setMinimumSize(QtCore.QSize(231, 68))
        self.OSL.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OSL.setFont(font)
        self.OSL.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"")
        self.OSL.setAlignment(QtCore.Qt.AlignCenter)
        self.OSL.setObjectName("OSL")
        self.gridLayout.addWidget(self.OSL, 4, 1, 1, 1)
        self.ID_Card = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ID_Card.setMinimumSize(QtCore.QSize(231, 68))
        self.ID_Card.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ID_Card.setFont(font)
        self.ID_Card.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"")
        self.ID_Card.setAlignment(QtCore.Qt.AlignCenter)
        self.ID_Card.setObjectName("ID_Card")
        self.gridLayout.addWidget(self.ID_Card, 9, 1, 1, 1)
        self.imgGas_Mask = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgGas_Mask.setMinimumSize(QtCore.QSize(88, 88))
        self.imgGas_Mask.setMaximumSize(QtCore.QSize(88, 88))
        self.imgGas_Mask.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgGas_Mask.setText("")
        self.imgGas_Mask.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/gas-mask.png"))
        self.imgGas_Mask.setScaledContents(True)
        self.imgGas_Mask.setObjectName("imgGas_Mask")
        self.gridLayout.addWidget(self.imgGas_Mask, 3, 0, 1, 1)
        self.imgID_Card = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgID_Card.setMinimumSize(QtCore.QSize(88, 88))
        self.imgID_Card.setMaximumSize(QtCore.QSize(88, 88))
        self.imgID_Card.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgID_Card.setText("")
        self.imgID_Card.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/ID_card.png"))
        self.imgID_Card.setScaledContents(True)
        self.imgID_Card.setObjectName("imgID_Card")
        self.gridLayout.addWidget(self.imgID_Card, 9, 0, 1, 1)
        self.imgOSL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgOSL.setMinimumSize(QtCore.QSize(88, 88))
        self.imgOSL.setMaximumSize(QtCore.QSize(88, 88))
        self.imgOSL.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgOSL.setText("")
        self.imgOSL.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/OSL.png"))
        self.imgOSL.setScaledContents(True)
        self.imgOSL.setObjectName("imgOSL")
        self.gridLayout.addWidget(self.imgOSL, 4, 0, 1, 1)
        self.imgFace_Shield = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgFace_Shield.setMinimumSize(QtCore.QSize(88, 88))
        self.imgFace_Shield.setMaximumSize(QtCore.QSize(88, 88))
        self.imgFace_Shield.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;\n"
"\n"
"")
        self.imgFace_Shield.setText("")
        self.imgFace_Shield.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/chemical_face_shield.png"))
        self.imgFace_Shield.setScaledContents(True)
        self.imgFace_Shield.setObjectName("imgFace_Shield")
        self.gridLayout.addWidget(self.imgFace_Shield, 1, 0, 1, 1)
        self.imgLong_Glove = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgLong_Glove.setMinimumSize(QtCore.QSize(88, 88))
        self.imgLong_Glove.setMaximumSize(QtCore.QSize(88, 88))
        self.imgLong_Glove.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgLong_Glove.setText("")
        self.imgLong_Glove.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/Long_yellow_gloves.png"))
        self.imgLong_Glove.setScaledContents(True)
        self.imgLong_Glove.setObjectName("imgLong_Glove")
        self.gridLayout.addWidget(self.imgLong_Glove, 7, 0, 1, 1)
        self.imgClothes = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgClothes.setMinimumSize(QtCore.QSize(88, 88))
        self.imgClothes.setMaximumSize(QtCore.QSize(88, 88))
        self.imgClothes.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgClothes.setText("")
        self.imgClothes.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/shirt.png"))
        self.imgClothes.setScaledContents(True)
        self.imgClothes.setObjectName("imgClothes")
        self.gridLayout.addWidget(self.imgClothes, 5, 0, 1, 1)
        self.imgSafety_Shoe = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgSafety_Shoe.setMinimumSize(QtCore.QSize(88, 88))
        self.imgSafety_Shoe.setMaximumSize(QtCore.QSize(88, 88))
        self.imgSafety_Shoe.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgSafety_Shoe.setText("")
        self.imgSafety_Shoe.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/safety_shoes.png"))
        self.imgSafety_Shoe.setScaledContents(True)
        self.imgSafety_Shoe.setObjectName("imgSafety_Shoe")
        self.gridLayout.addWidget(self.imgSafety_Shoe, 8, 0, 1, 1)
        self.imgCarbon_Mask = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgCarbon_Mask.setMinimumSize(QtCore.QSize(88, 88))
        self.imgCarbon_Mask.setMaximumSize(QtCore.QSize(88, 88))
        self.imgCarbon_Mask.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgCarbon_Mask.setText("")
        self.imgCarbon_Mask.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/mask.png"))
        self.imgCarbon_Mask.setScaledContents(True)
        self.imgCarbon_Mask.setObjectName("imgCarbon_Mask")
        self.gridLayout.addWidget(self.imgCarbon_Mask, 2, 0, 1, 1)
        self.imgGlove = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgGlove.setMinimumSize(QtCore.QSize(88, 88))
        self.imgGlove.setMaximumSize(QtCore.QSize(88, 88))
        self.imgGlove.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgGlove.setText("")
        self.imgGlove.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/glove.png"))
        self.imgGlove.setScaledContents(True)
        self.imgGlove.setObjectName("imgGlove")
        self.gridLayout.addWidget(self.imgGlove, 6, 0, 1, 1)
        self.Cap = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Cap.setMinimumSize(QtCore.QSize(231, 68))
        self.Cap.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Cap.setFont(font)
        self.Cap.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"")
        self.Cap.setObjectName("Cap")
        self.gridLayout.addWidget(self.Cap, 0, 1, 1, 1)
        self.Face_Shield = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Face_Shield.setMinimumSize(QtCore.QSize(231, 68))
        self.Face_Shield.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Face_Shield.setFont(font)
        self.Face_Shield.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"")
        self.Face_Shield.setObjectName("Face_Shield")
        self.gridLayout.addWidget(self.Face_Shield, 1, 1, 1, 1)
        self.imgCap = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgCap.setMinimumSize(QtCore.QSize(88, 88))
        self.imgCap.setMaximumSize(QtCore.QSize(88, 88))
        self.imgCap.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgCap.setText("")
        self.imgCap.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/cap.png"))
        self.imgCap.setScaledContents(True)
        self.imgCap.setObjectName("imgCap")
        self.gridLayout.addWidget(self.imgCap, 0, 0, 1, 1)
        self.Carbon_Mask = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Carbon_Mask.setMinimumSize(QtCore.QSize(231, 68))
        self.Carbon_Mask.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Carbon_Mask.setFont(font)
        self.Carbon_Mask.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"\n"
"")
        self.Carbon_Mask.setObjectName("Carbon_Mask")
        self.gridLayout.addWidget(self.Carbon_Mask, 2, 1, 1, 1)
        self.Gas_Mask = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Gas_Mask.setMinimumSize(QtCore.QSize(231, 68))
        self.Gas_Mask.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Gas_Mask.setFont(font)
        self.Gas_Mask.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"")
        self.Gas_Mask.setObjectName("Gas_Mask")
        self.gridLayout.addWidget(self.Gas_Mask, 3, 1, 1, 1)
        self.Long_Glove = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Long_Glove.setMinimumSize(QtCore.QSize(231, 68))
        self.Long_Glove.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Long_Glove.setFont(font)
        self.Long_Glove.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"\n"
"")
        self.Long_Glove.setAlignment(QtCore.Qt.AlignCenter)
        self.Long_Glove.setObjectName("Long_Glove")
        self.gridLayout.addWidget(self.Long_Glove, 7, 1, 1, 1)
        self.Glove = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Glove.setMinimumSize(QtCore.QSize(231, 68))
        self.Glove.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Glove.setFont(font)
        self.Glove.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"\n"
"")
        self.Glove.setAlignment(QtCore.Qt.AlignCenter)
        self.Glove.setObjectName("Glove")
        self.gridLayout.addWidget(self.Glove, 6, 1, 1, 1)
        self.Clothes = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Clothes.setMinimumSize(QtCore.QSize(231, 68))
        self.Clothes.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Clothes.setFont(font)
        self.Clothes.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"\n"
"")
        self.Clothes.setAlignment(QtCore.Qt.AlignCenter)
        self.Clothes.setObjectName("Clothes")
        self.gridLayout.addWidget(self.Clothes, 5, 1, 1, 1)
        self.Yellow_Jacket = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Yellow_Jacket.setMinimumSize(QtCore.QSize(231, 68))
        self.Yellow_Jacket.setMaximumSize(QtCore.QSize(231, 68))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Yellow_Jacket.setFont(font)
        self.Yellow_Jacket.setStyleSheet("background:    #A9A9A9;\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"\n"
"")
        self.Yellow_Jacket.setAlignment(QtCore.Qt.AlignCenter)
        self.Yellow_Jacket.setObjectName("Yellow_Jacket")
        self.gridLayout.addWidget(self.Yellow_Jacket, 10, 1, 1, 1)
        self.imgYellow_Jacket = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imgYellow_Jacket.setMinimumSize(QtCore.QSize(88, 88))
        self.imgYellow_Jacket.setMaximumSize(QtCore.QSize(88, 88))
        self.imgYellow_Jacket.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border: 2px solid rgb(74, 74, 74);\n"
"border-radius: 15px;")
        self.imgYellow_Jacket.setText("")
        self.imgYellow_Jacket.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/Yellow_Jacket.png"))
        self.imgYellow_Jacket.setScaledContents(True)
        self.imgYellow_Jacket.setObjectName("imgYellow_Jacket")
        self.gridLayout.addWidget(self.imgYellow_Jacket, 10, 0, 1, 1)
        self.lblIDcard = QtWidgets.QLabel(self.PPE)
        self.lblIDcard.setGeometry(QtCore.QRect(1520, 900, 351, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lblIDcard.setFont(font)
        self.lblIDcard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblIDcard.setAutoFillBackground(False)
        self.lblIDcard.setStyleSheet("background-color: rgb(41, 109, 157);\n"
"border-radius: 30px;\n"
"border: 2px solid rgb(47, 128, 182);\n"
"color: #ffffff;\n"
"\n"
"\n"
"")
        self.lblIDcard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblIDcard.setTextFormat(QtCore.Qt.PlainText)
        self.lblIDcard.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIDcard.setWordWrap(False)
        self.lblIDcard.setIndent(0)
        self.lblIDcard.setObjectName("lblIDcard")
        self.Reflabel = QtWidgets.QLabel(self.PPE)
        self.Reflabel.setGeometry(QtCore.QRect(1030, 160, 431, 721))
        self.Reflabel.setStyleSheet("border: 2px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.Reflabel.setText("")
        self.Reflabel.setScaledContents(True)
        self.Reflabel.setObjectName("Reflabel")
        self.imgsummary = QtWidgets.QLabel(self.PPE)
        self.imgsummary.setGeometry(QtCore.QRect(385, 140, 250, 250))
        self.imgsummary.setStyleSheet("background-color:none;\n"
"")
        self.imgsummary.setText("")
        self.imgsummary.setScaledContents(True)
        self.imgsummary.setObjectName("imgsummary")
        self.labelsummary = QtWidgets.QLabel(self.PPE)
        self.labelsummary.setGeometry(QtCore.QRect(145, 100, 731, 411))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.labelsummary.setFont(font)
        self.labelsummary.setStyleSheet("border-radius: 80px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"padding-top:280px;")
        self.labelsummary.setText("")
        self.labelsummary.setAlignment(QtCore.Qt.AlignCenter)
        self.labelsummary.setObjectName("labelsummary")
        self.Total_chemical = QtWidgets.QLabel(self.PPE)
        self.Total_chemical.setGeometry(QtCore.QRect(30, 930, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Total_chemical.setFont(font)
        self.Total_chemical.setStyleSheet("background-color: #06256c;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.Total_chemical.setAlignment(QtCore.Qt.AlignCenter)
        self.Total_chemical.setObjectName("Total_chemical")
        self.Total_solder = QtWidgets.QLabel(self.PPE)
        self.Total_solder.setGeometry(QtCore.QRect(490, 930, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Total_solder.setFont(font)
        self.Total_solder.setStyleSheet("background-color: #0b262b;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.Total_solder.setAlignment(QtCore.Qt.AlignCenter)
        self.Total_solder.setObjectName("Total_solder")
        self.Total_thickness = QtWidgets.QLabel(self.PPE)
        self.Total_thickness.setGeometry(QtCore.QRect(950, 930, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Total_thickness.setFont(font)
        self.Total_thickness.setStyleSheet("background-color:#333333;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.Total_thickness.setAlignment(QtCore.Qt.AlignCenter)
        self.Total_thickness.setObjectName("Total_thickness")
        self.MessageTime = QtWidgets.QLabel(self.PPE)
        self.MessageTime.setGeometry(QtCore.QRect(20, 100, 981, 731))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.MessageTime.setFont(font)
        self.MessageTime.setStyleSheet("background-color: white;\n"
"color: rgb(170, 0, 0);\n"
"padding-top:360px;")
        self.MessageTime.setAlignment(QtCore.Qt.AlignCenter)
        self.MessageTime.setObjectName("MessageTime")
        self.labelIDCard = QtWidgets.QLabel(self.PPE)
        self.labelIDCard.setGeometry(QtCore.QRect(0, 0, 1894, 1011))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.labelIDCard.setFont(font)
        self.labelIDCard.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelIDCard.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.523, x2:1, y2:0.556591, stop:0.0446429 rgba(52, 136, 197, 255), stop:1 rgba(183, 229, 238, 255));\n"
"padding-top:450px;\n"
"padding-right:1000px")
        self.labelIDCard.setTextFormat(QtCore.Qt.AutoText)
        self.labelIDCard.setScaledContents(False)
        self.labelIDCard.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelIDCard.setObjectName("labelIDCard")
        self.imglabel = QtWidgets.QLabel(self.PPE)
        self.imglabel.setGeometry(QtCore.QRect(1200, 250, 481, 401))
        self.imglabel.setStyleSheet("background-color: None;")
        self.imglabel.setText("")
        self.imglabel.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/card.png"))
        self.imglabel.setScaledContents(True)
        self.imglabel.setObjectName("imglabel")
        self.Dashboard = QtWidgets.QLabel(self.PPE)
        self.Dashboard.setGeometry(QtCore.QRect(0, 0, 951, 1011))
        self.Dashboard.setStyleSheet("background-color: #251306;")
        self.Dashboard.setText("")
        self.Dashboard.setScaledContents(True)
        self.Dashboard.setAlignment(QtCore.Qt.AlignCenter)
        self.Dashboard.setObjectName("Dashboard")
        self.PL_PPE = QtWidgets.QLabel(self.PPE)
        self.PL_PPE.setGeometry(QtCore.QRect(50, 40, 851, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.PL_PPE.setFont(font)
        self.PL_PPE.setStyleSheet("background-color: none;\n"
"color: #ce8a3a;")
        self.PL_PPE.setObjectName("PL_PPE")
        self.totalEnt = QtWidgets.QLabel(self.PPE)
        self.totalEnt.setGeometry(QtCore.QRect(275, 140, 401, 251))
        font = QtGui.QFont()
        font.setPointSize(54)
        font.setBold(True)
        font.setWeight(75)
        self.totalEnt.setFont(font)
        self.totalEnt.setStyleSheet("background-color: #391602;\n"
"border-radius: 40px;\n"
"color: white;\n"
"padding-top:40px")
        self.totalEnt.setAlignment(QtCore.Qt.AlignCenter)
        self.totalEnt.setObjectName("totalEnt")
        self.labelTotalEnt = QtWidgets.QLabel(self.PPE)
        self.labelTotalEnt.setGeometry(QtCore.QRect(275, 140, 401, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.labelTotalEnt.setFont(font)
        self.labelTotalEnt.setStyleSheet("color: #ce8a3a;\n"
"background-color: none;")
        self.labelTotalEnt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTotalEnt.setObjectName("labelTotalEnt")
        self.labelEoD = QtWidgets.QLabel(self.PPE)
        self.labelEoD.setGeometry(QtCore.QRect(345, 410, 254, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelEoD.setFont(font)
        self.labelEoD.setStyleSheet("background-color: #391602;\n"
"color: #ce8a3a;")
        self.labelEoD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEoD.setObjectName("labelEoD")
        self.GraphEoD = QtWidgets.QLabel(self.PPE)
        self.GraphEoD.setGeometry(QtCore.QRect(38, 492, 871, 491))
        self.GraphEoD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.GraphEoD.setText("")
        self.GraphEoD.setObjectName("GraphEoD")
        self.labelEmergency = QtWidgets.QLabel(self.PPE)
        self.labelEmergency.setGeometry(QtCore.QRect(0, 0, 1894, 1011))
        font = QtGui.QFont()
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.labelEmergency.setFont(font)
        self.labelEmergency.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"padding-top:380px;")
        self.labelEmergency.setText("")
        self.labelEmergency.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEmergency.setObjectName("labelEmergency")
        self.imgEmergency = QtWidgets.QLabel(self.PPE)
        self.imgEmergency.setGeometry(QtCore.QRect(662, 39, 571, 481))
        self.imgEmergency.setStyleSheet("background-color:none;\n"
"")
        self.imgEmergency.setText("")
        self.imgEmergency.setScaledContents(True)
        self.imgEmergency.setObjectName("imgEmergency")
        self.imgRFID = QtWidgets.QLabel(self.PPE)
        self.imgRFID.setGeometry(QtCore.QRect(727, 50, 441, 451))
        self.imgRFID.setStyleSheet("background-color:none;\n"
"")
        self.imgRFID.setText("")
        self.imgRFID.setScaledContents(True)
        self.imgRFID.setObjectName("imgRFID")
        self.labelRFID = QtWidgets.QLabel(self.PPE)
        self.labelRFID.setGeometry(QtCore.QRect(0, 0, 1894, 1011))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.labelRFID.setFont(font)
        self.labelRFID.setStyleSheet("background:none; \n"
"color:white; \n"
"padding-top:580px; ")
        self.labelRFID.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRFID.setObjectName("labelRFID")
        self.closebutton = QtWidgets.QPushButton(self.PPE)
        self.closebutton.setGeometry(QtCore.QRect(1820, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.closebutton.setFont(font)
        self.closebutton.setStyleSheet("background-color:none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon)
        self.closebutton.setIconSize(QtCore.QSize(65, 65))
        self.closebutton.setFlat(True)
        self.closebutton.setObjectName("closebutton")
        self.labelADAM = QtWidgets.QLabel(self.PPE)
        self.labelADAM.setGeometry(QtCore.QRect(730, 950, 1894, 1011))
        font = QtGui.QFont()
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.labelADAM.setFont(font)
        self.labelADAM.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"padding-top:380px;")
        self.labelADAM.setText("")
        self.labelADAM.setAlignment(QtCore.Qt.AlignCenter)
        self.labelADAM.setObjectName("labelADAM")
        self.imgADAM = QtWidgets.QLabel(self.PPE)
        self.imgADAM.setGeometry(QtCore.QRect(1030, 540, 571, 481))
        self.imgADAM.setStyleSheet("background-color:none;\n"
"")
        self.imgADAM.setText("")
        self.imgADAM.setScaledContents(True)
        self.imgADAM.setObjectName("imgADAM")
        self.Countnum.raise_()
        self.lblcategory.raise_()
        self.cameraview.raise_()
        self.DateTim.raise_()
        self.labelEquipment.raise_()
        self.lblGood.raise_()
        self.labelRef.raise_()
        self.lblNG.raise_()
        self.lblTotal.raise_()
        self.lblIDcard.raise_()
        self.Reflabel.raise_()
        self.Total_chemical.raise_()
        self.Total_solder.raise_()
        self.Total_thickness.raise_()
        self.groupBox.raise_()
        self.MessageTime.raise_()
        self.labelsummary.raise_()
        self.imgsummary.raise_()
        self.labelIDCard.raise_()
        self.imglabel.raise_()
        self.Dashboard.raise_()
        self.PL_PPE.raise_()
        self.totalEnt.raise_()
        self.labelTotalEnt.raise_()
        self.labelEoD.raise_()
        self.GraphEoD.raise_()
        self.labelRFID.raise_()
        self.imgRFID.raise_()
        self.labelADAM.raise_()
        self.imgADAM.raise_()
        self.labelEmergency.raise_()
        self.imgEmergency.raise_()
        self.closebutton.raise_()
        self.tabWidget.addTab(self.PPE, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DateTim.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy h:mm:ss AP"))
        self.lblcategory.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Section</p></body></html>"))
        self.labelEquipment.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Equipment to wear </span></p><p align=\"center\"><span style=\" font-size:24pt;\">Found / Missing</span></p></body></html>"))
        self.lblGood.setText(_translate("MainWindow", "<html><head/><body><p>Good :</p></body></html>"))
        self.lblNG.setText(_translate("MainWindow", "<html><head/><body><p>NG  :</p></body></html>"))
        self.lblTotal.setText(_translate("MainWindow", "<html><head/><body><p>Total :</p></body></html>"))
        self.Safety_Shoe.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Safety shoes</p></body></html>"))
        self.OSL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">OSL</p></body></html>"))
        self.ID_Card.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ID card</p></body></html>"))
        self.Cap.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Cap</p></body></html>"))
        self.Face_Shield.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Chemical Face Shield</p></body></html>"))
        self.Carbon_Mask.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mask</p></body></html>"))
        self.Gas_Mask.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Gas Mark</p></body></html>"))
        self.Long_Glove.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Long yellow glove</p></body></html>"))
        self.Glove.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Glove</p></body></html>"))
        self.Clothes.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Clothes</p></body></html>"))
        self.Yellow_Jacket.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Yellow Jacket</p></body></html>"))
        self.lblIDcard.setText(_translate("MainWindow", "ID Card"))
        self.Total_chemical.setText(_translate("MainWindow", "<html><head/><body><p>Chemical Analysis :</p></body></html>"))
        self.Total_solder.setText(_translate("MainWindow", "<html><head/><body><p>Solder Ability Test :</p></body></html>"))
        self.Total_thickness.setText(_translate("MainWindow", "<html><head/><body><p>Thickness Measurement :</p></body></html>"))
        self.MessageTime.setText(_translate("MainWindow", "<html><head/><body><p>หมดเวลาตรวจสอบ</p><p>โปรดสวมใส่อุปกรณให้ครบก่อน</p><p>ทำการตรวจสอบอีกครั้ง</p></body></html>"))
        self.labelIDCard.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Please Scan ID Card</p></body></html>"))
        self.PL_PPE.setText(_translate("MainWindow", "PL PPE Access Control Situation"))
        self.totalEnt.setText(_translate("MainWindow", "0"))
        self.labelTotalEnt.setText(_translate("MainWindow", "Total Entries"))
        self.labelEoD.setText(_translate("MainWindow", "Entries of Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PPE), _translate("MainWindow", "PPE"))
