# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\netuser003\Documents\manop\Branch\asset\SelectMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: #1E1E1E;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSAT = QtWidgets.QPushButton(self.centralwidget)
        self.btnSAT.setGeometry(QtCore.QRect(459, 290, 1022, 160))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.btnSAT.setFont(font)
        self.btnSAT.setStyleSheet("color: #C9DFEE;\n"
"background-color:  #0A84FF;\n"
"border-radius: 12px;\n"
"text-align: left;\n"
"padding-left: 170 px;\n"
"")
        self.btnSAT.setObjectName("btnSAT")
        self.btnTM = QtWidgets.QPushButton(self.centralwidget)
        self.btnTM.setGeometry(QtCore.QRect(459, 470, 1022, 160))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.btnTM.setFont(font)
        self.btnTM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnTM.setStyleSheet("color: #C9DFEE;\n"
"background-color:  #0A84FF;\n"
"border-radius: 12px;\n"
"text-align: left;\n"
"padding-left: 170 px;\n"
"")
        self.btnTM.setAutoDefault(False)
        self.btnTM.setDefault(False)
        self.btnTM.setFlat(False)
        self.btnTM.setObjectName("btnTM")
        self.btnCA = QtWidgets.QPushButton(self.centralwidget)
        self.btnCA.setGeometry(QtCore.QRect(460, 110, 1022, 160))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.btnCA.setFont(font)
        self.btnCA.setStyleSheet("color: #C9DFEE;\n"
"background-color:  #0A84FF;\n"
"border-radius: 12px;\n"
"text-align: left;\n"
"padding-left: 170 px;\n"
"")
        self.btnCA.setObjectName("btnCA")
        self.labelPS = QtWidgets.QLabel(self.centralwidget)
        self.labelPS.setGeometry(QtCore.QRect(460, 0, 1021, 111))
        font = QtGui.QFont()
        font.setPointSize(58)
        font.setBold(True)
        font.setWeight(75)
        self.labelPS.setFont(font)
        self.labelPS.setStyleSheet("background:    None;\n"
"\n"
"color: #F2F2F2;\n"
"")
        self.labelPS.setObjectName("labelPS")
        self.iconCA = QtWidgets.QLabel(self.centralwidget)
        self.iconCA.setGeometry(QtCore.QRect(470, 120, 140, 140))
        self.iconCA.setStyleSheet("background-color: #C9DFEE;\n"
"border-radius:10px")
        self.iconCA.setText("")
        self.iconCA.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/chemical_Analysis.png"))
        self.iconCA.setScaledContents(True)
        self.iconCA.setObjectName("iconCA")
        self.iconSAT = QtWidgets.QLabel(self.centralwidget)
        self.iconSAT.setGeometry(QtCore.QRect(470, 300, 140, 140))
        self.iconSAT.setStyleSheet("background-color: #C9DFEE;\n"
"border-radius:10px")
        self.iconSAT.setText("")
        self.iconSAT.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/solder_ability_test.png"))
        self.iconSAT.setScaledContents(True)
        self.iconSAT.setObjectName("iconSAT")
        self.iconTM = QtWidgets.QLabel(self.centralwidget)
        self.iconTM.setGeometry(QtCore.QRect(470, 480, 140, 140))
        self.iconTM.setStyleSheet("background-color: #C9DFEE;\n"
"border-radius:10px\n"
"")
        self.iconTM.setText("")
        self.iconTM.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/tape-measure.png"))
        self.iconTM.setScaledContents(True)
        self.iconTM.setObjectName("iconTM")
        self.btnGL = QtWidgets.QPushButton(self.centralwidget)
        self.btnGL.setGeometry(QtCore.QRect(459, 650, 1022, 160))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.btnGL.setFont(font)
        self.btnGL.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btnGL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnGL.setAutoFillBackground(False)
        self.btnGL.setStyleSheet("color: #C9DFEE;\n"
"background-color:  #0A84FF;\n"
"border-radius: 12px;\n"
"text-align: left;\n"
"padding-left: 170 px;\n"
"")
        self.btnGL.setAutoDefault(False)
        self.btnGL.setDefault(False)
        self.btnGL.setFlat(False)
        self.btnGL.setObjectName("btnGL")
        self.iconGL = QtWidgets.QLabel(self.centralwidget)
        self.iconGL.setGeometry(QtCore.QRect(470, 660, 140, 140))
        self.iconGL.setStyleSheet("background-color: #C9DFEE;\n"
"border-radius:10px")
        self.iconGL.setText("")
        self.iconGL.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/Group_lead.png"))
        self.iconGL.setScaledContents(True)
        self.iconGL.setObjectName("iconGL")
        self.btnMGR = QtWidgets.QPushButton(self.centralwidget)
        self.btnMGR.setGeometry(QtCore.QRect(459, 830, 1022, 160))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.btnMGR.setFont(font)
        self.btnMGR.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btnMGR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnMGR.setAutoFillBackground(False)
        self.btnMGR.setStyleSheet("color: #C9DFEE;\n"
"background-color:  #0A84FF;\n"
"border-radius: 12px;\n"
"text-align: left;\n"
"padding-left: 170 px;\n"
"")
        self.btnMGR.setAutoDefault(False)
        self.btnMGR.setDefault(False)
        self.btnMGR.setFlat(False)
        self.btnMGR.setObjectName("btnMGR")
        self.iconMGR = QtWidgets.QLabel(self.centralwidget)
        self.iconMGR.setGeometry(QtCore.QRect(470, 840, 140, 140))
        self.iconMGR.setStyleSheet("background-color: #C9DFEE;\n"
"border-radius:10px")
        self.iconMGR.setText("")
        self.iconMGR.setPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/Manager.png"))
        self.iconMGR.setScaledContents(True)
        self.iconMGR.setObjectName("iconMGR")
        self.closebtnSelect = QtWidgets.QPushButton(self.centralwidget)
        self.closebtnSelect.setGeometry(QtCore.QRect(1819, 30, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.closebtnSelect.setFont(font)
        self.closebtnSelect.setStyleSheet("background-color:none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\netuser003\\Documents\\manop\\Branch\\asset\\Image/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebtnSelect.setIcon(icon)
        self.closebtnSelect.setIconSize(QtCore.QSize(65, 65))
        self.closebtnSelect.setFlat(True)
        self.closebtnSelect.setObjectName("closebtnSelect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSAT.setText(_translate("MainWindow", "Solder Ability Test"))
        self.btnTM.setText(_translate("MainWindow", "Thickness measurement"))
        self.btnCA.setText(_translate("MainWindow", "Chemical Ananlysis"))
        self.labelPS.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Please Select</p></body></html>"))
        self.btnGL.setText(_translate("MainWindow", "Group Lead"))
        self.btnMGR.setText(_translate("MainWindow", "Manager"))
